server:
  port: 8080

spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/space_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      format-sql: true
  liquibase:
    change-log: /db/changelog-master.xml
    enabled: true
    drop-first: false
    default-schema: public

jwt:
  secret: f645838f3cc57af453f5e18efb0028064db7fc8a6f26e989c2ecf536a6bbb025f5f4c21057e4c0b74353c9a956fb48510d954470a677a4435f9ad14fb4259e95bf3335b12967ed74ae1cf5cf3241801c71610913ab3d8215c1e0af2510704ff3cfe4390670f0008911223c127235f6972fbae469233d9c0b057b1ffd8973bafd
  expiration-ms: 3600000
refresh-token:
  expiration-days: 7

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
